apiVersion: v1
kind: Service
metadata:
  name: employee-frontend
  namespace: employee-system
spec:
  type: NodePort
  selector:
    app: employee-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
